# Generated by Django 3.2.3 on 2022-11-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
